/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime false --config wrangler.jsonc` (hash: bc1624424f04a1bb62f6cf683ac7446d)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env {
		OTP_STATE: KVNamespace;
		R2_PUBLIC_URL: "https://data-herbarium.columbina.kr";
		TOTP_STORE_KEY: "virtual-herbarium:totp-store:v1";
		TOTP_STORE_ALLOW_BOOTSTRAP: "false";
		LOGO_OBJECT_KEY: "virtual-herbarium/UI/logo.svg";
		TOTP_STORE_ENCRYPTION_KEY: string;
		AUTH_TOKEN_SECRET: string;
		ADMIN_TOTP_SECRET: string;
		HERBARIUM_BUCKET: R2Bucket;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_PUBLIC_URL" | "TOTP_STORE_KEY" | "TOTP_STORE_ALLOW_BOOTSTRAP" | "LOGO_OBJECT_KEY" | "TOTP_STORE_ENCRYPTION_KEY" | "AUTH_TOKEN_SECRET" | "ADMIN_TOTP_SECRET">> {}
}
